@startuml
title OLA 3\n Components Diagram
Actor User

node "PuppetEnterprise" {
  [Code Manager\nr10k] as r10k
  [Master]
  [PuppetDB]
  [Console]
  interface "TCP:8170" as TCP8170
  interface "TCP:443" as TCP443
  interface "TCP:8080" as TCP8080
  interface "TCP:8140" as TCP8140
  interface "TCP:4433" as TCP4433
  [Console] - TCP443
  [Console] - TCP4433
  r10k - TCP8170
  [PuppetDB] - TCP8080
  [Master] - TCP8140
}

node "MARS\nApache" as MARS {
  [Puppet Forge]
  [Repositorios RHEL7]
  [Artifacts]
}

node "GitLab" {
  [git]
  interface "GIT:te-controlrepo" as controlrepo
  [git] - controlrepo
}
cloud "Internet" {
}
database "PostgreSQL" {
  [postgresql]
  interface "TCP:5432" as TCP5432
  [postgresql] - TCP5432
}
cloud "Automalia" {
}
node "Node" {
  [Puppet\nAgent]
  interface SSH
}
Automalia -> SSH
Automalia -> TCP8080
User -> TCP443
r10k -> controlrepo
r10k -> [Puppet Forge]
[Puppet\nAgent] -> MARS : 22, 80, 443
[Puppet\nAgent] -> TCP8140
MARS -> Internet : proxy 80, 443
[PuppetDB] -> TCP5432
[Console] -> TCP5432
[git] -> TCP8170 : webhook
@enduml
