@startuml
title OLA 3\n Components Diagram
Actor User

node "PuppetEnterprise" {
  [Code Manager\nr10k] as r10k
  [Master]
  [PuppetDB]
  [Console]
  interface "TCP:8170" as TCP8170
  interface "TCP:443" as TCP443
  interface "TCP:8080\nTCP:8081" as TCP8081
  interface "TCP:8140" as TCP8140
  [Console] - TCP443
  r10k - TCP8170
  [PuppetDB] - TCP8081
  [Master] - TCP8140
}

node MARS {
  [Apache]
  [Puppet Forge]
  [Repositorios RHEL7]
  [Artifacts]
  interface "TCP:80\nTCP:443" as TCPMARS
  [Apache] - TCPMARS
}

node "GitLab" {
  [git]
  interface "GIT:controlrepo" as controlrepo
  [git] - controlrepo
}
cloud "Internet" {
  [forge.puppet.com]
}
database "PostgreSQL" {
  [postgresql]
  interface "TCP:5432" as TCP5432
  [postgresql] - TCP5432
}
cloud "Automalia" {
}
cloud "Node" {
  [Puppet\nAgent]
  interface SSH
}

cloud "External CA" {
  [Intermediate CA]
  interface "API CA" as APICA
  [Intermediate CA] - APICA
}
  
Automalia -> SSH
Automalia -> TCP8081
Automalia -> controlrepo
User -> TCP443
r10k -> controlrepo
r10k -> TCPMARS
[Puppet Forge] -> [forge.puppet.com]
[Puppet\nAgent] -> TCPMARS
[Puppet\nAgent] -> TCP8140
Node -> APICA
[PuppetDB] -> TCP5432
[Console] -> TCP5432
[git] -> TCP8170
@enduml
