@startuml

title OLA3\n Sequence Diagram

actor User
participant "Automalia" as A
participant "gitlab" as B
participant "PE" as C
participant "MARS" as D
participant "Node" as E
participant "CA" as F
database "PuppetDB" as G


User -> A: Deploy app
activate A

A -> B: Write hiera file
activate B

B -> C: Update controlrepo
activate C

C -> D: Get modules
activate D

D --> C
deactivate D

C --> B
deactivate C

B --> A
deactivate B

A -> E: Bootstrap node
activate E

E -> C: Get Puppet Agent
activate C

C --> E
deactivate C

E -> F: Sign and get node certificate
activate F

F --> E
deactivate F

E --> A
deactivate E

A -> E: Run Puppet Agent
activate E

E -> C: Get catalog
activate C

C --> E
deactivate C

E -> E: Apply catalog

E -> D: Get software
activate D

D --> E
deactivate D

E -> C: Report node status
activate C

C -> G: Store node status
activate G

G --> C
deactivate G

C --> E
deactivate C

E --> A
deactivate E

A -> G: Check node status
activate G

G --> A
deactivate G

A --> User: Node deployed
deactivate A

@enduml
