@startuml

title PaaS Dinamico\n Sequence Diagram

actor User
participant "Automalia" as A
participant "gitlab" as B
participant "PE" as C
participant "MARS" as D
participant "Node" as E
participant "CA" as F
database "PuppetDB" as G


User -> A: Bootstrap node
activate A

A -> B: Write hiera file
activate B

B -> C: r10k code update
activate C

C -> D: Get modules
activate D

D --> C
deactivate D

C --> B
deactivate C

B --> A
deactivate B

A -> E: Deploy node
activate E

E -> C: Get Puppet Agent
activate C

C --> E
deactivate C

E -> F: Get signer certificates
activate F

F --> E
deactivate F

E --> A
deactivate E

A -> E: Run Puppet Agent
activate E

E -> C: Get catalog
activate C

C --> E
deactivate C

E -> E: Apply catalog

E -> G: Store metadata
activate G

G --> E
deactivate G

E --> A
deactivate E

A --> User: Node deployed
deactivate A

@enduml
